### ISSUE TITLE
Link to Original Mish Repository

### ISSUE THREAD

**Issue by digantamisra98** [pabloppp/pytorch-tools#2]
Hi. 
Would appreciate if you added the link to the original Mish Repository. I keep dding more results and analysis there. Thanks! 
Link - https://github.com/digantamisra98/Mish

**Comment by pabloppp** [comment]
Absolutely! So sorry for not giving you the proper credits 🙇
It's been already fixed in here https://github.com/pabloppp/pytorch-tools/commit/f4b62e81869c94dc7e4ec905e9ddca435e5f4a95 thank you for your awesome work!!!!

And sorry again 🙇🙇🙇🙇🙇
